nice:
  - Nice
  - Lovely 
  - Superior 
  - Swell 
  - Admirable
  - Attractive 
  - Commendable
  - Delightful
  - Fine
  - Gracious 
  - Inviting
  - Peachy 
  - Pleasant 
  - Well-manned
  - Premium 
  - Sick
  - Sweet
  - Resplendent 
  - Neat
  - Outstanding 

cock:
  - Cock
  - Dong 
  - Penis
  - Pebus 
  - Shlong 
  - Weiner 
  - Dick
  - Phallus
  - Tallywacker
  - Shaft 
  - Knob
  - Wang
  - Pecker
  - Wenie 
  - Ramrod 
  - Willy
  - Prick
  - Erection
  - Plonker 
  - Johnson 

bro:
  - Bro
  - Brother 
  - Friend 
  - My Friend 
  - Dude 
  - Pal 
  - Guy 
  - Buddy 
  - Boon Companion
  - Ally 
  - Colleague
  - Partner
  - Chum
  - Playmate
  - Comrade 
  - Mate 
  - Compatriot 
  - Associate
  - Confidante
  - Compeer